### PR TITLE
Readme edits and contributing

### PR DESCRIPTION
**Pull request by ondine**
@bbourbie Need clarification on the config file examples. Is it 'https://api.splunknova.com' or 'https://api-username.splunknova.com' or ''https://api-username.splunknovadev.com:443' 
Also is access to the docker hub repo: https://hub.docker.com/r/polarishq/fluentd_splunknova still using the polarishq prefix?

### CODE REVIEW

**Comment by ondine** [comment]
meant to branch again before changing .DS_Store in 360b8fd.

**Comment by ondine** [comment]
PR #2 add .DS_Store to .gitignore is now on it's own branch

**Comment by bbourbie** [comment]
@ondine  Yes, you are right, 'https://api-username.splunknova.com' or ''https://api-username.splunknovadev.com:443' is more for us, the developers/ testers. 

Yes, it's still using the PolarisHQ prefix for the moment, @hyfather, do you think we can start renaming everything to Splunk Nova

**Comment by hyfather** [comment]
@ondine @bbourbie yes let's use `https://api.splunknova.com:443` across all documentation everywhere.
The dockerhub polarishq repo is fine for now, let's plan to migrate it to a splunknova docker org soon.

**Pull request closed without merging**
